import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Header";
import NextTopLoader from "nextjs-toploader";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader
          color="green"
          height={3}
          showSpinner={false}
        />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
